version: '3.8'

services:
  seko-cycles:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - web-internal
    environment:
      - TZ=America/New_York
      - PLAYWRIGHT_BROWSERS_PATH=/app/pw-browsers
    secrets:
      - bigquery_credentials
      - seko_env_file
    configs:
      - source: seko_crontab
        target: /etc/cron.d/seko-cron
        mode: 0644
    deploy:
      mode: replicated
      replicas: 1
      placement:
        # Can run on any manager node
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 300s
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      labels:
        # No external Traefik access needed - this is a background job
        - "traefik.enable=false"
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  web-internal:
    external: true

secrets:
  bigquery_credentials:
    external: true
  seko_env_file:
    external: true

configs:
  seko_crontab:
    external: true