version: '3.8'

services:
  seko-cycles:
    image: ghcr.io/washcyclist/seko-scraper:latest  # You need to build and push this first
    networks:
      - web-internal
    environment:
      - TZ=America/New_York
      - PLAYWRIGHT_BROWSERS_PATH=/app/pw-browsers
    secrets:
      - bigquery_credentials
      - seko_env_file
    configs:
      - source: seko_crontab
        target: /etc/cron.d/seko-cron
        mode: 0644
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  web-internal:
    external: true

secrets:
  bigquery_credentials:
    external: true
  seko_env_file:
    external: true

configs:
  seko_crontab:
    external: true